package com.mydrinksapp.ui.allingredients.ingredients

class IngredientsProvider {
    companion object {
        val ingredienstList = mutableListOf<Ingredients>(
            Ingredients("Light rum"),
            Ingredients("Applejack"),
            Ingredients("Gin"),
            Ingredients("Dark rum"),
            Ingredients("Sweet Vermouth"),
            Ingredients("Strawberry schnapps"),
            Ingredients("Scotch"),
            Ingredients("Apricot brandy"),
            Ingredients("Triple sec"),
            Ingredients("Southern Comfort"),
            Ingredients("Orange bitters"),
            Ingredients("Brandy"),
            Ingredients("Lemon vodka"),
            Ingredients("Blended whiskey"),
            Ingredients("Dry Vermouth"),
            Ingredients("Amaretto"),
            Ingredients("Tea"),
            Ingredients("Champagne"),
            Ingredients("Coffee liqueur"),
            Ingredients("Bourbon"),
            Ingredients("Tequila"),
            Ingredients("Vodka"),
            Ingredients("Añejo rum"),
            Ingredients("Bitters"),
            Ingredients("Sugar"),
            Ingredients("Kahlua"),
            Ingredients("demerara Sugar"),
            Ingredients("Dubonnet Rouge"),
            Ingredients("Watermelon"),
            Ingredients("Lime juice"),
            Ingredients("Irish whiskey"),
            Ingredients("Apple brandy"),
            Ingredients("Carbonated water"),
            Ingredients("Cherry brandy"),
            Ingredients("Creme de Cacao"),
            Ingredients("Grenadine"),
            Ingredients("Port"),
            Ingredients("Coffee brandy"),
            Ingredients("Red wine"),
            Ingredients("Rum"),
            Ingredients("Grapefruit juice"),
            Ingredients("Ricard"),
            Ingredients("Sherry"),
            Ingredients("Cognac"),
            Ingredients("Sloe gin"),
            Ingredients("Apple juice"),
            Ingredients("Pineapple juice"),
            Ingredients("Lemon juice"),
            Ingredients("Sugar syrup"),
            Ingredients("Milk"),
            Ingredients("Strawberries"),
            Ingredients("Chocolate syrup"),
            Ingredients("Yoghurt"),
            Ingredients("Mango"),
            Ingredients("Ginger"),
            Ingredients("Lime"),
            Ingredients("Cantaloupe"),
            Ingredients("Berries"),
            Ingredients("Grapes"),
            Ingredients("Kiwi"),
            Ingredients("Tomato juice"),
            Ingredients("Cocoa powder"),
            Ingredients("Chocolate"),
            Ingredients("Heavy cream"),
            Ingredients("Galliano"),
            Ingredients("Peach Vodka"),
            Ingredients("Ouzo"),
            Ingredients("Coffee"),
            Ingredients("Spiced rum"),
            Ingredients("Water"),
            Ingredients("Espresso"),
            Ingredients("Angelica root"),
            Ingredients("Orange"),
            Ingredients("Cranberries"),
            Ingredients("Johnnie Walker"),
            Ingredients("Apple cider"),
            Ingredients("Everclear"),
            Ingredients("Cranberry juice"),
            Ingredients("Egg yolk"),
            Ingredients("Egg"),
            Ingredients("Grape juice"),
            Ingredients("Peach nectar"),
            Ingredients("Lemon"),
            Ingredients("Firewater"),
            Ingredients("Lemonade"),
            Ingredients("Lager"),
            Ingredients("Whiskey"),
            Ingredients("Absolut Citron"),
            Ingredients("Pisco"),
            Ingredients("Irish cream"),
            Ingredients("Ale"),
            Ingredients("Chocolate liqueur"),
            Ingredients("Midori melon liqueur"),
            Ingredients("Sambuca"),
            Ingredients("Cider"),
            Ingredients("Sprite"),
            Ingredients("7-Up"),
            Ingredients("Blackberry brandy"),
            Ingredients("Peppermint schnapps"),
            Ingredients("Creme de Cassis")
        )
    }
}